name: Attach Release Notes

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  attach-release-notes:
    runs-on: ubuntu-20.04

    steps:
      - name: Install gh CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Get previous release tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAGS=($(gh api repos/${{ github.repository }}/releases --jq '.[0].tag_name, .[1].tag_name'))
          CURRENT_TAG=${TAGS[0]}
          PREVIOUS_TAG=${TAGS[1]}

          echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV
          echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_ENV

      - name: Create diff log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DIFF_LOG=$(gh api repos/${{ github.repository }}/compare/$PREVIOUS_TAG...$CURRENT_TAG --jq '.commits | map("- " + .commit.message) | join("\n")')

          echo "DIFF_LOG<<EOF" >> $GITHUB_ENV
          echo "$DIFF_LOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Fetch GitHub Release body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_BODY=$(gh release view $LATEST_TAG --repo ${{ github.repository }} --json body -q .body)

          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Assemble release_notes.md
        run: |
          FILE="release_notes.md"

          echo "# Release Notes for $CURRENT_TAG" > $FILE
          echo "" >> $FILE
          echo "## Summary" >> $FILE
          echo "$RELEASE_BODY" >> $FILE
          echo "" >> $FILE
          echo "## Changes Since $PREVIOUS_TAG" >> $FILE
          echo "$DIFF_LOG" >> $FILE